name: Release

permissions:
  contents: write
  issues: read
  pull-requests: read

on:
  push:
    tags: ['v*']

env:
  CI: true

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Run type checking
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test

      - name: Build Chrome extension
        run: pnpm build

      - name: Build Firefox extension
        run: pnpm build:firefox

      - name: Package Chrome extension
        run: pnpm zip

      - name: Package Firefox extension
        run: pnpm zip:firefox

      - name: Generate release notes
        id: release_notes
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Generate release notes from recent commits
          echo "## Changes" > release_notes.md
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD~1)..HEAD >> release_notes.md || echo "- Initial release" >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            .output/*.zip
          body_path: release_notes.md
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Future: Auto-submit to stores (requires secrets setup)
      # - name: Submit to Chrome Web Store
      #   run: pnpm wxt submit --chrome --dry-run
      #   env:
      #     CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
      #     CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
      #     CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
      #     CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
      #
      # - name: Submit to Firefox Add-ons
      #   run: pnpm wxt submit --firefox --dry-run
      #   env:
      #     FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
      #     FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
      #     FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
